import { CheckCircle2, ChevronLeft, Clock3, MapPin, PackageCheck, ReceiptText } from 'lucide-react'
import { Link } from 'react-router-dom'
import { StorefrontHeader } from '@/features/customer/shared/StorefrontHeader'
import { StorefrontFooter } from '@/features/customer/shared/StorefrontFooter'

const orders = [
  { id: 'ORD-200720-02', date: '20 ก.ค. 2569', period: 'รอบเช้า 09:00–10:00', location: 'จุดรับสินค้า A', total: '150 บาท', status: 'กำลังเตรียมของ', items: 'ลูกชิ้นเนื้อเอ็น 5 ไม้, น้ำเก๊กฮวยเย็น 2 แก้ว' },
  { id: 'ORD-190720-01', date: '19 ก.ค. 2569', period: 'รอบบ่าย 14:00–15:00', location: 'จุดรับสินค้า B', total: '115 บาท', status: 'ส่งแล้ว', items: 'น้ำเก๊กฮวยเย็น 3 แก้ว, ลูกชิ้นเนื้อเอ็น 2 ไม้' },
]

export function MyOrdersPage() {
  return <section className="min-h-screen overflow-hidden"><StorefrontHeader /><main className="mx-auto w-full max-w-[960px] px-6 py-8 max-md:px-3.5 max-md:py-5"><Link to="/" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#76503a] px-5 text-xl font-extrabold text-white no-underline shadow-md shadow-[#76503a]/20 transition hover:bg-[#5f3d2b]"><ChevronLeft size={22} strokeWidth={2.75} aria-hidden="true" /> เลือกเมนูเพิ่ม</Link><div className="mt-5"><h1 className="m-0 font-heading text-[clamp(2rem,5vw,3rem)] text-ink">ออเดอร์ของฉัน</h1></div><div className="mt-3 grid gap-4">{orders.map((order) => <article key={order.id} className="rounded-2xl border border-[#b9cbbf] bg-white p-5 shadow-sm max-md:p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="m-0 text-base font-bold text-muted">{order.id} · {order.date}</p><h2 className="mt-1 mb-0 font-heading text-2xl text-ink">{order.status}</h2></div><span className={`inline-flex min-h-9 items-center rounded-full px-3 text-base font-extrabold ${order.status === 'ส่งแล้ว' ? 'bg-[#def2e1] text-[#287b3b]' : 'bg-[#fff3e0] text-[#9c5b18]'}`}>{order.status === 'ส่งแล้ว' ? <CheckCircle2 className="mr-1.5" size={18} aria-hidden="true" /> : <Clock3 className="mr-1.5" size={18} aria-hidden="true" />}{order.status}</span></div><div className="mt-5 grid gap-3 border-t border-[#e2e8e3] pt-4 text-lg text-[#455048]"><p className="m-0 flex items-start gap-2"><PackageCheck className="mt-0.5 shrink-0 text-brand" size={20} aria-hidden="true" /><span>{order.items}</span></p><p className="m-0 flex items-center gap-2"><MapPin className="shrink-0 text-brand" size={20} aria-hidden="true" />{order.location} · {order.period}</p><p className="m-0 flex items-center justify-between gap-4"><span className="inline-flex items-center gap-2"><ReceiptText className="text-brand" size={20} aria-hidden="true" />ยอดชำระ</span><strong className="font-heading text-xl text-brand">{order.total}</strong></p></div></article>)}</div></main><StorefrontFooter /></section>
}
