import { Check, MessageCircle, Pencil, Plus, Trash2, X } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { AdminTablePagination } from '@/features/admin/shared/AdminTablePagination'
import { confirmDelete } from '@/components/sweetalert2/confirm-delete'
import { badgeCountLabel } from '@/utils/badge-count'
import { useDeleteUser, useSaveUser, useUsers } from './hooks/useUsers'

export function UserTable() {
  const usersQuery = useUsers(); const saveMutation = useSaveUser(); const deleteMutation = useDeleteUser(); const [page, setPage] = useState(1); const pageSize = 10
  const users = usersQuery.data ?? []; const visibleUsers = users.slice((page - 1) * pageSize, page * pageSize)
  async function deleteUser(userId: number, userName: string) { if (!await confirmDelete(`ผู้ใช้งาน “${userName}”`)) return; await deleteMutation.mutateAsync(userId); setPage((current) => Math.min(current, Math.max(1, Math.ceil((users.length - 1) / pageSize)))) }
  function toggleUser(userId: number) { const user = users.find((item) => item.id === userId); if (!user) return; saveMutation.mutate({ userId, input: { name: user.name, phone: user.phone, lineId: user.lineId, locationId: user.locationId, isActive: !user.isActive, password: '', confirmPassword: '' } }) }
  return <section className="admin-page product-page"><div className="admin-page-heading"><div><h1 className="admin-title">ผู้ใช้งาน</h1></div><Link to="/admin/users/add" className="admin-primary-button"><Plus size={19} aria-hidden="true" />เพิ่มผู้ใช้งาน</Link></div><div className="product-table-wrap"><div className="product-table-scroll"><table className="product-table user-table"><thead><tr><th className="table-row-number">ลำดับ</th><th>ชื่อลูกค้า</th><th>เบอร์โทรศัพท์</th><th>LINE ID</th><th>จุดรับสินค้า</th><th>เปิดการใช้งาน</th><th>จัดการ</th></tr></thead><tbody>{usersQuery.isLoading && <tr><td colSpan={7}>กำลังโหลดผู้ใช้งาน...</td></tr>}{usersQuery.isError && <tr><td colSpan={7}>ไม่สามารถโหลดผู้ใช้งานได้: {usersQuery.error.message}</td></tr>}{!usersQuery.isLoading && !usersQuery.isError && !visibleUsers.length && <tr><td colSpan={7}>ยังไม่มีผู้ใช้งาน</td></tr>}{visibleUsers.map((user, index) => <tr key={user.id}><td className="table-row-number">{(page - 1) * pageSize + index + 1}</td><td><strong>{user.name}</strong></td><td className="numeric">{user.phone}</td><td>{user.lineId}</td><td>{user.locationName}</td><td><button className={`product-display-status ${user.isActive ? 'is-active' : 'is-inactive'}`} type="button" disabled={saveMutation.isPending} aria-pressed={user.isActive} aria-label={`${user.isActive ? 'ปิด' : 'เปิด'}การใช้งาน ${user.name}`} onClick={() => toggleUser(user.id)}>{user.isActive ? <Check size={19} aria-hidden="true" /> : <X size={19} aria-hidden="true" />}</button></td><td><div className="product-actions"><Link className="user-message-action" to={`/admin/users/${user.id}/chat`} aria-label={`${user.messageCount ? `มีข้อความ ${user.messageCount} ข้อความ, ` : ''}ส่งข้อความถึง ${user.name}`} title="ส่งข้อความ"><MessageCircle size={17} aria-hidden="true" />{user.messageCount > 0 && <span className="user-message-count" aria-hidden="true">{badgeCountLabel(user.messageCount)}</span>}</Link><Link className="product-edit" to={`/admin/users/${user.id}/edit`} aria-label={`แก้ไข ${user.name}`}><Pencil size={17} aria-hidden="true" /></Link><button className="product-delete" type="button" disabled={deleteMutation.isPending} aria-label={`ลบ ${user.name}`} onClick={() => deleteUser(user.id, user.name)}><Trash2 size={17} aria-hidden="true" /></button></div></td></tr>)}</tbody></table></div><AdminTablePagination currentPage={page} totalItems={users.length} pageSize={pageSize} onPageChange={setPage} label="ผู้ใช้งาน" /></div></section>
}
